services:
  - type: web
    name: hubtv-backend
    env: node
    plan: free
    buildCommand: npm install --legacy-peer-deps
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
